#!/bin/bash

# Генерируем случайное четырехзначное число
number=$(shuf -i 1000-9999 -n 1)

echo "Число загадано. Попробуйте угадать."
echo "$number"

while true; do
    read guess < /tmp/guess_pipe
    if [[ $guess =~ ^[0-9]{4}$ ]]; then
        bulls=0
        cows=0
        for ((i=0; i<4; i++)); do
            if [[ ${guess:i:1} == ${number:i:1} ]]; then
                bulls=$((bulls + 1))
            elif [[ $number == *${guess:i:1}* ]]; then
                cows=$((cows + 1))
            fi
        done
        echo "Быки: $bulls, Коровы: $cows" > /tmp/response_pipe
        if [ $bulls -eq 4 ]; then
            echo "Поздравляю, вы угадали!" > /tmp/response_pipe
            break
        fi
    else
        echo "Введите четырехзначное число." > /tmp/response_pipe
    fi
done


